# Generated by Django 4.2.2 on 2023-06-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savininkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone_number', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skaitiklis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skaitiklio_vieta', models.CharField(choices=[('Šaltas vonios', 'Šaltas vonios'), ('Šaltas virtuvės', 'Šaltas virtuvės'), ('Karštas vonios', 'Karštas vonios'), ('Karštas virtuvės', 'Karštas virtuvės')], max_length=80)),
                ('iki_reiksme', models.IntegerField(max_length=5, verbose_name='Iki')),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Butas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buto_numeris', models.IntegerField(max_length=2)),
                ('buto_plotas', models.IntegerField(max_length=3)),
                ('zmoniu_skaicius', models.IntegerField(max_length=2)),
                ('savininkas', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.savininkas')),
            ],
        ),
    ]
