# Generated by Django 4.2.2 on 2023-06-25 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skaitiklis',
            name='update_at',
        ),
        migrations.AddField(
            model_name='skaitiklis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skaitiklis',
            name='nuo_reiksme',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nuo'),
        ),
        migrations.AlterField(
            model_name='butas',
            name='buto_numeris',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='butas',
            name='buto_plotas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='butas',
            name='zmoniu_skaicius',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savininkas',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skaitiklis',
            name='iki_reiksme',
            field=models.IntegerField(verbose_name='Iki'),
        ),
    ]
