# Generated by Django 4.2.2 on 2023-06-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0002_remove_skaitiklis_update_at_skaitiklis_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skaitiklis',
            name='butas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.butas'),
        ),
        migrations.AddField(
            model_name='skaitiklis',
            name='skirtumas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
