# Generated by Django 4.2.2 on 2023-06-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0003_skaitiklis_butas_skaitiklis_skirtumas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyvatukas', models.IntegerField(verbose_name='Gyvatukas')),
                ('bendra_elektra', models.IntegerField(verbose_name='Bendra elektra')),
                ('karsto_vandens_ikainis', models.IntegerField(verbose_name='Karšto vandens įkainis')),
                ('salto_vandens_ikainis', models.IntegerField(verbose_name='Šalto vandens įkainis')),
                ('kaupiamasis', models.IntegerField(verbose_name='Kaupiamieji remontui')),
                ('administravimo', models.IntegerField(verbose_name='Administravimo mokestis')),
                ('butas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.butas')),
                ('skaitiklis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.skaitiklis')),
            ],
        ),
    ]
