# Generated by Django 4.2.2 on 2023-06-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0005_elektrosskaitiklis_remove_saskaita_butas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butas',
            options={'verbose_name': 'Butas', 'verbose_name_plural': 'Butai'},
        ),
        migrations.AlterModelOptions(
            name='elektrosskaitiklis',
            options={'verbose_name': 'Elektros skaitilis', 'verbose_name_plural': 'Elektros skaitikliai'},
        ),
        migrations.AlterModelOptions(
            name='saskaita',
            options={'verbose_name': 'Sąskaita', 'verbose_name_plural': 'Sąskaitos'},
        ),
        migrations.AlterModelOptions(
            name='savininkas',
            options={'verbose_name': 'Savininkas', 'verbose_name_plural': 'Savininkai'},
        ),
        migrations.AlterModelOptions(
            name='skaitiklis',
            options={'verbose_name': 'Skaitiklis', 'verbose_name_plural': 'Skaitikliai'},
        ),
        migrations.AddField(
            model_name='saskaita',
            name='karsto_vandens_kiekis',
            field=models.IntegerField(null=True, verbose_name='Suvartoto karšto vandens kiekis'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='salto_vandens_kiekis',
            field=models.IntegerField(null=True, verbose_name='Suvartoto šalto vandens kiekis'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='skaitiklis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.skaitiklis'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='suma_karsto_vandens',
            field=models.FloatField(null=True, verbose_name='Už karštą vandenį'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='suma_salto_vandens',
            field=models.FloatField(null=True, verbose_name='Už šaltą vandenį'),
        ),
        migrations.AlterField(
            model_name='elektrosskaitiklis',
            name='buto_el',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='bendra_elektra',
            field=models.FloatField(verbose_name='Bendra elektra'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='gyvatukas',
            field=models.FloatField(verbose_name='Gyvatukas'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='karsto_vandens_ikainis',
            field=models.FloatField(verbose_name='Karšto vandens įkainis'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='salto_vandens_ikainis',
            field=models.FloatField(verbose_name='Šalto vandens įkainis'),
        ),
    ]
