# Generated by Django 4.2.2 on 2023-06-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0006_alter_butas_options_alter_elektrosskaitiklis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elektrosskaitiklis',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='butas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.butas'),
        ),
    ]
