# Generated by Django 4.2.2 on 2023-06-29 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0007_elektrosskaitiklis_update_at_saskaita_butas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sildymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bendra_sildymo_suma', models.FloatField(null=True, verbose_name='Bendra suma už šildymą')),
                ('buto_sildymas', models.FloatField(null=True, verbose_name='Šildymas')),
                ('butas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buhalterija.butas')),
            ],
            options={
                'verbose_name': 'Šildymas',
            },
        ),
    ]
