# Generated by Django 4.2.2 on 2023-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0008_sildymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskaita',
            name='bendra_sildymo_suma',
            field=models.FloatField(null=True, verbose_name='Bendra suma už šildymą'),
        ),
        migrations.AddField(
            model_name='saskaita',
            name='buto_sildymas',
            field=models.FloatField(null=True, verbose_name='Šildymas'),
        ),
        migrations.DeleteModel(
            name='Sildymas',
        ),
    ]
