# Generated by Django 4.2.2 on 2023-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0009_saskaita_bendra_sildymo_suma_saskaita_buto_sildymas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskaita',
            name='moketi',
            field=models.FloatField(default=0, verbose_name='Iš viso mokėti'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='administravimo',
            field=models.IntegerField(default=0, verbose_name='Administravimo mokestis'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='bendra_elektra',
            field=models.FloatField(default=0, verbose_name='Bendra elektra'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='bendra_sildymo_suma',
            field=models.FloatField(default=0, verbose_name='Bendra suma už šildymą'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='buto_sildymas',
            field=models.FloatField(default=0, verbose_name='Šildymas'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='gyvatukas',
            field=models.FloatField(default=0, verbose_name='Gyvatukas'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='karsto_vandens_kiekis',
            field=models.IntegerField(default=0, verbose_name='Suvartoto karšto vandens kiekis'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='kaupiamasis',
            field=models.IntegerField(default=0, verbose_name='Kaupiamieji remontui'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='salto_vandens_kiekis',
            field=models.IntegerField(default=0, verbose_name='Suvartoto šalto vandens kiekis'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='suma_karsto_vandens',
            field=models.FloatField(default=0, verbose_name='Už karštą vandenį'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='suma_salto_vandens',
            field=models.FloatField(default=0, verbose_name='Už šaltą vandenį'),
        ),
    ]
