# Generated by Django 4.2.2 on 2023-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhalterija', '0010_saskaita_moketi_alter_saskaita_administravimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saskaita',
            name='administravimo',
            field=models.FloatField(default=0, verbose_name='Administravimo mokestis'),
        ),
        migrations.AlterField(
            model_name='saskaita',
            name='kaupiamasis',
            field=models.FloatField(default=0, verbose_name='Kaupiamieji remontui'),
        ),
    ]
